apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ts-express-starter
  annotations:
    github.com/project-slug: edr3x/ts-express-starter
spec:
  type: other
  lifecycle: unknown
  owner: edr3x
